Add solution for evaluations.
GeorgiMinkov/DI-Final-Exam-FMI pull request #8
Opened 2019-06-09 09:02 UTC by KristinStefanova

2019-06-09 16:25 UTC, GeorgiMinkov approved these changes
All good (INNA - Me Gusta : 0:57)

2019-06-11 21:45 UTC, NickyMateev requested changes

2019-06-11 21:45 UTC, NickyMateev commented on Information-system (Информационни системи)/Писмен (practical)/07.2016/task-3.hs
> +-- 2. [map(f5)[1,2,3]|f<­[(+),(­),(*)]]
Spaces between map arguments would be needed

`f 5` instead of `f5`

`f<-[...` instead of `f<[...`

`(-)` instead of `()`

2019-06-11 21:45 UTC, NickyMateev commented on Information-system (Информационни системи)/Писмен (practical)/07.2016/task-3.hs
> +-- 1. [x:[x]|x<­[[1,2],[3,4]]]
`x<-[...` instead of `x<[...`

2019-06-11 21:45 UTC, NickyMateev commented on Information-system (Информационни системи)/Писмен (practical)/07.2016/task-3.hs
> +-- Оценка: "a" = ['a'] : ["bc", "d"] = ["a", "bc", "d"]
`"a" = ` shouldn't be here

2019-07-15 12:36 UTC, closed without merging